# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReSTedSyncReSTMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from MyTextEdit import MyTextEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1552, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
#        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit = MyTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tabCSS = QtWidgets.QWidget()
        self.tabCSS.setObjectName("tabCSS")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabCSS)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEditCSS = QtWidgets.QPlainTextEdit(self.tabCSS)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setItalic(False)
        self.plainTextEditCSS.setFont(font)
        self.plainTextEditCSS.setObjectName("plainTextEditCSS")
        self.gridLayout_3.addWidget(self.plainTextEditCSS, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabCSS, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.webView = QtWebKitWidgets.QWebView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout.addWidget(self.webView)
        self.tabWidget.addTab(self.tab_2, "")
        self.tabCode = QtWidgets.QWidget()
        self.tabCode.setObjectName("tabCode")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabCode)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textCode = QtWidgets.QTextEdit(self.tabCode)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        self.textCode.setFont(font)
        self.textCode.setReadOnly(True)
        self.textCode.setObjectName("textCode")
        self.gridLayout_4.addWidget(self.textCode, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabCode, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.infoToolsLayout = QtWidgets.QHBoxLayout()
        self.infoToolsLayout.setContentsMargins(-1, -1, -1, 3)
        self.infoToolsLayout.setObjectName("infoToolsLayout")
        self.gboxPosition = QtWidgets.QGroupBox(self.centralwidget)
        self.gboxPosition.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gboxPosition.setFlat(True)
        self.gboxPosition.setObjectName("gboxPosition")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gboxPosition)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelPosition = QtWidgets.QLabel(self.gboxPosition)
        self.labelPosition.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelPosition.setObjectName("labelPosition")
        self.horizontalLayout.addWidget(self.labelPosition)
        self.labModifiedText = QtWidgets.QLabel(self.gboxPosition)
        self.labModifiedText.setMinimumSize(QtCore.QSize(0, 24))
        self.labModifiedText.setMaximumSize(QtCore.QSize(115, 16))
        self.labModifiedText.setObjectName("labModifiedText")
        self.horizontalLayout.addWidget(self.labModifiedText)
        self.labModifiedIcon = QtWidgets.QLabel(self.gboxPosition)
        self.labModifiedIcon.setMaximumSize(QtCore.QSize(11, 11))
        self.labModifiedIcon.setText("")
        self.labModifiedIcon.setPixmap(QtGui.QPixmap("resources/emptyCircleIcon10.png"))
        self.labModifiedIcon.setObjectName("labModifiedIcon")
        self.horizontalLayout.addWidget(self.labModifiedIcon)
        self.horizontalWidget = QtWidgets.QWidget(self.gboxPosition)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.gboxSync = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.gboxSync.setObjectName("gboxSync")
        self.labCSSSyncText = QtWidgets.QLabel(self.horizontalWidget)
        self.labCSSSyncText.setMaximumSize(QtCore.QSize(80, 16))
        self.labCSSSyncText.setObjectName("labCSSSyncText")
        self.gboxSync.addWidget(self.labCSSSyncText)
        self.labCSSSyncIcon = QtWidgets.QLabel(self.horizontalWidget)
        self.labCSSSyncIcon.setMinimumSize(QtCore.QSize(11, 11))
        self.labCSSSyncIcon.setMaximumSize(QtCore.QSize(11, 11))
        self.labCSSSyncIcon.setText("")
        self.labCSSSyncIcon.setPixmap(QtGui.QPixmap("resources/emptyCircleIcon10.png"))
        self.labCSSSyncIcon.setObjectName("labCSSSyncIcon")
        self.gboxSync.addWidget(self.labCSSSyncIcon)
        self.labHTMLSyncText = QtWidgets.QLabel(self.horizontalWidget)
        self.labHTMLSyncText.setMaximumSize(QtCore.QSize(95, 16))
        self.labHTMLSyncText.setObjectName("labHTMLSyncText")
        self.gboxSync.addWidget(self.labHTMLSyncText)
        self.labHTMLSyncIcon = QtWidgets.QLabel(self.horizontalWidget)
        self.labHTMLSyncIcon.setMinimumSize(QtCore.QSize(11, 11))
        self.labHTMLSyncIcon.setMaximumSize(QtCore.QSize(11, 11))
        self.labHTMLSyncIcon.setText("")
        self.labHTMLSyncIcon.setPixmap(QtGui.QPixmap("resources/emptyCircleIcon10.png"))
        self.labHTMLSyncIcon.setObjectName("labHTMLSyncIcon")
        self.gboxSync.addWidget(self.labHTMLSyncIcon)
        self.horizontalLayout.addWidget(self.horizontalWidget)
        self.infoToolsLayout.addWidget(self.gboxPosition)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.infoToolsLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.infoToolsLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1552, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReST_history = QtWidgets.QMenu(self.menuFile)
        self.menuReST_history.setObjectName("menuReST_history")
        self.menuCSS_history = QtWidgets.QMenu(self.menuFile)
        self.menuCSS_history.setObjectName("menuCSS_history")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        self.menuReST = QtWidgets.QMenu(self.menubar)
        self.menuReST.setObjectName("menuReST")
        self.menuLists = QtWidgets.QMenu(self.menuReST)
        self.menuLists.setObjectName("menuLists")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSaveReST = QtWidgets.QAction(MainWindow)
        self.actionSaveReST.setObjectName("actionSaveReST")
        self.actionSaveHTML = QtWidgets.QAction(MainWindow)
        self.actionSaveHTML.setObjectName("actionSaveHTML")
        self.actionConvert = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.actionConvert.setIcon(icon)
        self.actionConvert.setObjectName("actionConvert")
        self.actionLoadReST = QtWidgets.QAction(MainWindow)
        self.actionLoadReST.setObjectName("actionLoadReST")
        self.actionLoadCSS = QtWidgets.QAction(MainWindow)
        self.actionLoadCSS.setObjectName("actionLoadCSS")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSaveCSS = QtWidgets.QAction(MainWindow)
        self.actionSaveCSS.setObjectName("actionSaveCSS")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionSave_ReST = QtWidgets.QAction(MainWindow)
        self.actionSave_ReST.setObjectName("actionSave_ReST")
        self.actionClearReSTHistory = QtWidgets.QAction(MainWindow)
        self.actionClearReSTHistory.setObjectName("actionClearReSTHistory")
        self.actionClearCSSHistory = QtWidgets.QAction(MainWindow)
        self.actionClearCSSHistory.setObjectName("actionClearCSSHistory")
        self.actionSearch_Replace_dialog = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("edit-find-replace")
        self.actionSearch_Replace_dialog.setIcon(icon)
        self.actionSearch_Replace_dialog.setObjectName("actionSearch_Replace_dialog")
        self.actionForward = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.actionForward.setIcon(icon)
        self.actionForward.setObjectName("actionForward")
        self.actionBack = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.actionBack.setIcon(icon)
        self.actionBack.setObjectName("actionBack")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("undo")
        self.actionUndo.setIcon(icon)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("redo")
        self.actionRedo.setIcon(icon)
        self.actionRedo.setObjectName("actionRedo")
        self.actionBulleted = QtWidgets.QAction(MainWindow)
        self.actionBulleted.setObjectName("actionBulleted")
        self.actionEnumerated = QtWidgets.QAction(MainWindow)
        self.actionEnumerated.setObjectName("actionEnumerated")
        self.actionDefinition = QtWidgets.QAction(MainWindow)
        self.actionDefinition.setObjectName("actionDefinition")
        self.actionField = QtWidgets.QAction(MainWindow)
        self.actionField.setObjectName("actionField")
        self.actionOption = QtWidgets.QAction(MainWindow)
        self.actionOption.setObjectName("actionOption")
        self.menuReST_history.addSeparator()
        self.menuCSS_history.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoadReST)
        self.menuFile.addAction(self.menuReST_history.menuAction())
        self.menuFile.addAction(self.actionLoadCSS)
        self.menuFile.addAction(self.menuCSS_history.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveReST)
        self.menuFile.addAction(self.actionSave_ReST)
        self.menuFile.addAction(self.actionSaveHTML)
        self.menuFile.addAction(self.actionSaveCSS)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionConvert)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuSearch.addAction(self.actionSearch_Replace_dialog)
        self.menuLists.addAction(self.actionBulleted)
        self.menuLists.addAction(self.actionEnumerated)
        self.menuLists.addAction(self.actionDefinition)
        self.menuLists.addAction(self.actionField)
        self.menuLists.addAction(self.actionOption)
        self.menuReST.addAction(self.menuLists.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuReST.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionConvert)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBack)
        self.toolBar.addAction(self.actionForward)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSearch_Replace_dialog)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setStatusTip(_translate("MainWindow", "ReStructured text -- input"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ReStructured text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCSS), _translate("MainWindow", "CSS"))
        self.webView.setStatusTip(_translate("MainWindow", "HTML view -- output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "HTML view"))
        self.tabCode.setToolTip(_translate("MainWindow", "HTML code"))
        self.tabCode.setStatusTip(_translate("MainWindow", "HTML code"))
        self.textCode.setToolTip(_translate("MainWindow", "HTML code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCode), _translate("MainWindow", "Code"))
        self.labelPosition.setText(_translate("MainWindow", "l. x c.:"))
        self.labModifiedText.setText(_translate("MainWindow", "ReST Modified:"))
        self.labCSSSyncText.setText(_translate("MainWindow", "CSS Sync:"))
        self.labHTMLSyncText.setText(_translate("MainWindow", "HTML Sync:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuReST_history.setTitle(_translate("MainWindow", "ReST history"))
        self.menuCSS_history.setTitle(_translate("MainWindow", "CSS history"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSearch.setTitle(_translate("MainWindow", "Search"))
        self.menuReST.setTitle(_translate("MainWindow", "ReST"))
        self.menuLists.setTitle(_translate("MainWindow", "Lists"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSaveReST.setText(_translate("MainWindow", "Save ReST as..."))
        self.actionSaveHTML.setText(_translate("MainWindow", "Save HTML as..."))
        self.actionConvert.setText(_translate("MainWindow", "Convert"))
        self.actionConvert.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionLoadReST.setText(_translate("MainWindow", "Load ReST"))
        self.actionLoadReST.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionLoadCSS.setText(_translate("MainWindow", "Load CSS"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSaveCSS.setText(_translate("MainWindow", "Save CSS as..."))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionSave_ReST.setText(_translate("MainWindow", "Save ReST"))
        self.actionSave_ReST.setStatusTip(_translate("MainWindow", "Save ReST"))
        self.actionSave_ReST.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionClearReSTHistory.setText(_translate("MainWindow", "Clear history"))
        self.actionClearCSSHistory.setText(_translate("MainWindow", "Clear history"))
        self.actionSearch_Replace_dialog.setText(_translate("MainWindow", "Search/Replace dialog"))
        self.actionForward.setText(_translate("MainWindow", "Forward"))
        self.actionForward.setToolTip(_translate("MainWindow", "Go forward"))
        self.actionBack.setText(_translate("MainWindow", "Back"))
        self.actionBack.setToolTip(_translate("MainWindow", "Go back"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionBulleted.setText(_translate("MainWindow", "Bulleted"))
        self.actionBulleted.setToolTip(_translate("MainWindow", "Selection into bulleted list"))
        self.actionEnumerated.setText(_translate("MainWindow", "Enumerated"))
        self.actionEnumerated.setToolTip(_translate("MainWindow", "Selection into enumerated list"))
        self.actionDefinition.setText(_translate("MainWindow", "Definition"))
        self.actionDefinition.setToolTip(_translate("MainWindow", "Selection into definition list"))
        self.actionField.setText(_translate("MainWindow", "Field"))
        self.actionField.setToolTip(_translate("MainWindow", "Selection into field list"))
        self.actionOption.setText(_translate("MainWindow", "Option"))
        self.actionOption.setToolTip(_translate("MainWindow", "Selection into option list"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

