# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchReplaceDlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    """ Custom search/replace dialog """

    def __init__(self, flags):
        self.FLAGS = flags
        # print("D>>>>>>>>>>>>>>>>>>>> SearchReplaceDlg.FLAGS =", self.FLAGS)


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(582, 308)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("edit-find-replace")
        Dialog.setWindowIcon(icon)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 581, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEditSearch = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.verticalLayout_8.addWidget(self.lineEditSearch)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbIgnoreCase = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbIgnoreCase.setObjectName("cbIgnoreCase")
        self.verticalLayout_4.addWidget(self.cbIgnoreCase)
        self.cbWholeWords = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbWholeWords.setObjectName("cbWholeWords")
        self.verticalLayout_4.addWidget(self.cbWholeWords)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pbFind = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbFind.setObjectName("pbFind")
        self.verticalLayout_7.addWidget(self.pbFind)
        self.pbFindNext = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbFindNext.setObjectName("pbFindNext")
        self.verticalLayout_7.addWidget(self.pbFindNext)
        self.pbFindPrev = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbFindPrev.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbFindPrev.setObjectName("pbFindPrev")
        self.verticalLayout_7.addWidget(self.pbFindPrev)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEditReplace = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditReplace.setEnabled(False)
        self.lineEditReplace.setObjectName("lineEditReplace")
        self.horizontalLayout_5.addWidget(self.lineEditReplace)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cbReplace = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cbReplace.setObjectName("cbReplace")
        self.verticalLayout_10.addWidget(self.cbReplace)
        self.pbReplace = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbReplace.setEnabled(False)
        self.pbReplace.setObjectName("pbReplace")
        self.verticalLayout_10.addWidget(self.pbReplace)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lbNoMatches = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbNoMatches.setObjectName("lbNoMatches")
        self.verticalLayout_13.addWidget(self.lbNoMatches)
        self.lbPosition = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbPosition.setObjectName("lbPosition")
        self.verticalLayout_13.addWidget(self.lbPosition)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_11.setContentsMargins(140, -1, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pbClose = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbClose.setMaximumSize(QtCore.QSize(100, 32))
        self.pbClose.setObjectName("pbClose")
        self.verticalLayout_11.addWidget(self.pbClose)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.actionFind = QtWidgets.QAction(Dialog)
        icon = QtGui.QIcon.fromTheme("edit-find")
        self.actionFind.setIcon(icon)
        self.actionFind.setObjectName("actionFind")
        self.actionfindPrev = QtWidgets.QAction(Dialog)
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.actionfindPrev.setIcon(icon)
        self.actionfindPrev.setObjectName("actionfindPrev")
        self.actionenableReplace = QtWidgets.QAction(Dialog)
        self.actionenableReplace.setObjectName("actionenableReplace")
        self.actionReplace = QtWidgets.QAction(Dialog)
        icon = QtGui.QIcon.fromTheme("edit-find-replace")
        self.actionReplace.setIcon(icon)
        self.actionReplace.setObjectName("actionReplace")
        self.actionClose = QtWidgets.QAction(Dialog)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.actionFind_next = QtWidgets.QAction(Dialog)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.actionFind_next.setIcon(icon)
        self.actionFind_next.setObjectName("actionFind_next")
        self.actionWholeWords = QtWidgets.QAction(Dialog)
        self.actionWholeWords.setObjectName("actionWholeWords")

        self.retranslateUi(Dialog)
        self.pbFind.clicked.connect(self.actionFind.trigger)
        self.pbFindPrev.clicked.connect(self.actionfindPrev.trigger)
        self.cbReplace.stateChanged['int'].connect(self.actionenableReplace.trigger)
        self.pbReplace.clicked.connect(self.actionReplace.trigger)
        self.pbClose.clicked.connect(self.actionClose.trigger)
        self.lineEditReplace.returnPressed.connect(self.actionReplace.trigger)
        self.lineEditSearch.returnPressed.connect(self.pbFind.click)
        self.pbFindNext.clicked.connect(self.actionFind_next.trigger)
        self.cbWholeWords.stateChanged['int'].connect(self.actionWholeWords.trigger)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Search/Replace"))
        self.label.setText(_translate("Dialog", "Search:"))
        self.cbIgnoreCase.setText(_translate("Dialog", "Ignore case"))
        self.cbWholeWords.setText(_translate("Dialog", "Whole words"))
        self.pbFind.setToolTip(_translate("Dialog", "Find, find next"))
        self.pbFind.setText(_translate("Dialog", "Find"))
        self.pbFindNext.setText(_translate("Dialog", "Find next"))
        self.pbFindPrev.setToolTip(_translate("Dialog", "Find previous"))
        self.pbFindPrev.setText(_translate("Dialog", "Find prev."))
        self.label_2.setText(_translate("Dialog", "Replace:"))
        self.cbReplace.setToolTip(_translate("Dialog", "Enable replace"))
        self.cbReplace.setText(_translate("Dialog", "Replace"))
        self.pbReplace.setToolTip(_translate("Dialog", "Replace"))
        self.pbReplace.setText(_translate("Dialog", "Replace"))
        self.label_3.setText(_translate("Dialog", "Matches:"))
        self.label_4.setText(_translate("Dialog", "Current position:"))
        self.lbNoMatches.setText(_translate("Dialog", "-"))
        self.lbPosition.setText(_translate("Dialog", "-"))
        self.pbClose.setText(_translate("Dialog", "Close"))
        self.actionFind.setText(_translate("Dialog", "Find"))
        self.actionFind.setToolTip(_translate("Dialog", "Find, Find next"))
        self.actionFind.setStatusTip(_translate("Dialog", "Find, Find next"))
        self.actionfindPrev.setText(_translate("Dialog", "findPrev"))
        self.actionfindPrev.setToolTip(_translate("Dialog", "Find previous"))
        self.actionenableReplace.setText(_translate("Dialog", "enableReplace"))
        self.actionReplace.setText(_translate("Dialog", "Replace"))
        self.actionClose.setText(_translate("Dialog", "Close"))
        self.actionFind_next.setText(_translate("Dialog", "Find next"))
        self.actionFind_next.setToolTip(_translate("Dialog", "Find next"))
        self.actionWholeWords.setText(_translate("Dialog", "WholeWords"))
        self.actionWholeWords.setToolTip(_translate("Dialog", "Whole words only"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

